services:
  whisper-api:
    build: 
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - WHISPER_MODEL=base
      - REDIS_URL=redis://redis:6379/0
      - MODEL_CACHE_DIR=/app/models
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - whisper-network
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 6G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - whisper-network

volumes:
  redis_data:
  
networks:
  whisper-network:
    driver: bridge
