services:
  whisper-api:
    build: 
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - WHISPER_MODEL=base
      - REDIS_URL=redis://redis:6379/0
      - CACHE_DIR=/app/models  # 修正：避免與 model_ 前綴衝突
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - whisper-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - whisper-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --url http://nginx:80 --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - whisper-network
    depends_on:
      - nginx
      - whisper-api
    env_file:
      - .env.cloudflare
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - whisper-api
    restart: unless-stopped
    networks:
      - whisper-network

volumes:
  redis_data:
  
networks:
  whisper-network:
    driver: bridge
